version: '3'

# 名前つきボリューム
volumes:
  mysql_data:
services:
  client_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/client_app/'
    ports:
      - '3006:3006'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db:database
    networks:
      - default
      - shared-network
  db:
    image: mysql:8.0
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3311:3311'

networks:
  shared-network:
    external: true
